require("prototypes.recipe.ore-processing.base")
require("prototypes.recipe.no-hand-crafting.burner-assembling-machine")
require("prototypes.recipe.cokery.base")
require("prototypes.recipe.tree-farm.base")
require("prototypes.recipe.water-well.base")