require("prototypes.item.ore-processing.base")
require("prototypes.item.no-hand-crafting.burner-assembling-machine")
require("prototypes.item.cokery.base")
require("prototypes.item.tree-farm.base")
require("prototypes.item.water-well.base")