require("prototypes.entity.ore-processing.base")
require("prototypes.entity.no-hand-crafting.burner-assembling-machine")
require("prototypes.entity.cokery.base")
--require("prototypes.entity.tree-farm.base")
require("prototypes.entity.water-well.base")
require("prototypes.entity.terraform.base")
require("prototypes.entity.biofarm.base")